In [2]:
pip install datasets

Requirement already satisfied: datasets in /home/pateisreal/ds_env/lib/python3.12/site-packages (4.8.4)
Requirement already satisfied: filelock in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (2.4.3)
Requirement already satisfied: pyarrow>=21.0.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (3.0.1)
Requirement already satisfied: requests>=2.32.2 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (2.33.0)
Requirement already satisfied: httpx<1.0.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /home/pateisreal/ds_env/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /home/pateisreal/ds_env/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/pateisreal/ds_env/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /home/pateisreal/ds_env/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.2)
Requirement already satisfied: typer in /home/pateisreal/ds_env/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.26 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/pateisreal/ds_env/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
# load the dataset

from datasets import load_from_disk

items  = load_from_disk("/home/pateisreal/Desktop/dataset/item_dataset_final_top2000")
reviews = load_from_disk("/home/pateisreal/Desktop/dataset/review_dataset_final_top2000")

# convert to pandas
items_df = items.to_pandas()
reviews_df = reviews.to_pandas()

In [12]:
items_df.head(5)

                                                                                                 title  average_rating  rating_number                                                                                             features                                                                                          description  price parent_asin                                                 image_url
0                  Fire TV Stick with Alexa Voice Remote, streaming media player - Previous Generation            4.48          32163  [Our best-selling Fire TV Stick, with the 1st Gen Alexa Voice Remote., Enjoy tens of thousands o...                                                                                                   []   None  B075X8471B  https://m.media-amazon.com/images/I/51JuZsJ5yGL._AC_.jpg
1                                         Echo Dot (2nd Generation) - Smart speaker with Alexa - White            4.43          29600  [Echo Dot is a voice-controlled speaker that uses Alexa to play music, control smart home device...                                                                                                   []  39.99  B01K8B8YA8  https://m.media-amazon.com/images/I/4162wAg-X8L._AC_.jpg
2      Fire TV Stick 4K streaming device with Alexa Voice Remote (includes TV controls) | Dolby Vision            4.56          26150  [Cinematic experience - Watch in vibrant 4K Ultra HD with support for Dolby Vision, HDR, and HDR...                                                                                                   []   None  B07GZFM1ZM  https://m.media-amazon.com/images/I/41-hUFPN2dL._AC_.jpg
3    Fire Tablet with Alexa, 7" Display, 16 GB, Blue - with Special Offers (Previous Generation - 5th)            4.25          17887  [Beautiful 7" IPS display and 1.3 GHz quad-core processor. Available in four colors., Now with t...                                                                                                   []   None  B010BWYDYA  https://m.media-amazon.com/images/I/515dMUkeoYL._AC_.jpg
4  Panasonic ErgoFit Wired Earbuds, In-Ear Headphones with Microphone and Call Controller, Ergonomi...            4.33          15892  [The RP-TCM125 ErgoFit Earbud Headphones with Microphone and Call Controller are the perfect com...  [The Panasonic RP-TCM125 ErgoFit Earbud Headphones with Microphone and Call Controller are the p...  13.99  B07S764D9V  https://m.media-amazon.com/images/I/41mcJ3vWMNL._AC_.jpg

In [13]:
items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           2000 non-null   str
 1   average_rating  2000 non-null   float64
 2   rating_number   2000 non-null   int64
 3   features        2000 non-null   object
 4   description     2000 non-null   object
 5   price           2000 non-null   str
 6   parent_asin     2000 non-null   str
 7   image_url       2000 non-null   str
dtypes: float64(1), int64(1), object(2), str(4)
memory usage: 503.0+ KB

In [10]:
reviews_df.head(5)

   rating                                                                      title                                                                                                 text parent_asin                       user_id
0     5.0                                          Love the headphones - great range  These are fantastic headphones and I love that i can have my cell phone plugged in at a central ...  B09S6Y5BRG  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ
1     5.0                                                                 Five Stars                                                                           pretty good for the price.  B01LW71IBJ  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ
2     5.0                                                             BUY THIS THANG       yes.. so good.  just buy it. my favorite feature is it auto connects and remembers my devices.  B017T99JPG  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ
3     1.0  Not sure why this has good reviews. My devices had a hard time connecting  This devices brought my wifi network to its knees. Not sure why this has good reviews. My device...  B00L0YLRUW  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ
4     3.0                                                    Works but corners crack  Works well, but the corner of the plastic cracked and is broken after a month or so. I think at ...  B01HHURN3W  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ

In [11]:
reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2815510 entries, 0 to 2815509
Data columns (total 5 columns):
 #   Column       Dtype
---  ------       -----
 0   rating       float64
 1   title        str
 2   text         str
 3   parent_asin  str
 4   user_id      str
dtypes: float64(1), str(4)
memory usage: 910.3 MB

In [14]:
reviews_df = reviews_df.rename(columns={"parent_asin": "item_id"})
ratings_df = reviews_df[["user_id", "item_id", "rating"]].copy()

In [16]:
items_df = items_df.rename(columns={"parent_asin": "item_id"})
items_df = items_df[[
    "item_id",
    "title",
    "features",
    "description",
    "image_url"
]]

In [18]:
products = set(items_df["item_id"].unique())
ratings_df = ratings_df[ratings_df["item_id"].isin(products)]
data = ratings_df.merge(items_df, on="item_id", how="inner")
data.head(5)

                        user_id     item_id  rating                                                                                                title                                                                                             features                                                                                          description                                                 image_url
0  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B09S6Y5BRG     5.0  Otium Bluetooth Earbuds Wireless Headphones Bluetooth Headphones, Sports Earbuds, IPX7 Waterproo...  [True HD High Fidelity Sound.Update Bluetooth Headphones own latest Bluetooth 5.1 technology and...                                                                                                   []  https://m.media-amazon.com/images/I/41sN-XYld0L._AC_.jpg
1  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0                               Logitech Z313 Speaker System + Logitech Bluetooth Audio Adapter Bundle  [The control pod makes it easy to control volume and headphone controls, You can fill your room ...                                                                                                   []  https://m.media-amazon.com/images/I/41S1uuypGRL._AC_.jpg
2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0                                                    Bose SoundLink Mini Bluetooth Speaker II (Carbon)  [Big sound with deep bass for a full range listening experience, Wireless and ultra compact so y...  [It's the small speaker with the big, big voice. The SoundLink Mini Bluetooth speaker II deliver...  https://m.media-amazon.com/images/I/41SqVGnpzUL._AC_.jpg
3  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  NETGEAR Wi-Fi Range Extender EX2700 - Coverage Up to 800 Sq Ft and 10 devices with N300 Wireless...  [N300 WI-FI speed: Provides up to 300 Mbps performance.Connectivity protocol:Ethernet,Wi-Fi, Uni...  [Say goodbye to Wi-Fi dead zones. Convenient, discreet and easy to install, extended Wi-Fi cover...  https://m.media-amazon.com/images/I/31mI-til0gL._AC_.jpg
4  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  Besdata Magnetic Smart Cover & Translucent Back Case with Screen Protector, Cleaning Cloth and S...  [It protects the back as well as the screen, while maintaining the thin and light design of your...  [- 2 SEPARATED PIECES DESIGN: It protects the back as well as the screen, while maintaining the ...  https://m.media-amazon.com/images/I/31sa8fBSGQL._AC_.jpg

In [19]:
data.to_csv("/home/pateisreal/projects/ML_project/ML-project/data/processed/products.csv", index=False)